name: Validate CSR Common Name
on:
  pull_request:
    paths:
      - '**/*.csr'

jobs:
  validate-csr-cn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: |
            *.csr
          sparse-checkout-cone-mode: false

      - name: Get changed CSR files
        id: changed_csrs
        run: |
          files=$(git diff --name-only --diff-filter=AMR ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.csr$' | xargs)
          echo "csr_files=$files" >> $GITHUB_OUTPUT

      - name: Validate each CSR
        if: ${{ steps.changed_csrs.outputs.csr_files }}
        run: |
          for csr in ${{ steps.changed_csrs.outputs.csr_files }}; do
            echo $csr
            filename=$(echo $csr | awk -F "[/.]" '{ print $2 }')
            echo $filename
            ls -l $filename
            cat $csr
            set -x
            openssl req -in $csv -noout -subject
            set +x
          done
